### ISSUE TITLE
Tweak usage when there is only one input VCF

### ISSUE THREAD

**Issue by MarieLataretu** [jonas-fuchs/virHEAT#14]
Hi @jonas-fuchs, thanks for this tool :)

I tested virHEAT on one sample with the default parameters and run into the error, that there is nothing to plot:

```
virheat vcf out -l $LEN # only one file in the vcf folder
Frequency array seems to be empty. There is nothing to plot.
```

At first, I thought that my VCF file has an incompatible format. But actually,  `delete_common_mutations` removes all mutations and `delete` is `true` by default:
https://github.com/jonas-fuchs/virHEAT/blob/07e59b3c0b7adcfec673cc3a17f340fa68772a70/virheat/command.py#L160-L161

It perfectly works with one sample and `--no-delete`!

I think it would be nice to warn the user (and suggest using `--no-delete`) or skip `delete_common_mutations` (even if `delete` is `true`), if there is only one input VCF.

**Comment by jonas-fuchs** [comment]
Thanks for the feedback! I will do this in the next update. Might switch the default just to 'no-delete' or ignore it if just one sample is used 👍👍👍
