### ISSUE TITLE
GFF error when using a mtDNA annotation file

### ISSUE THREAD

**Issue by hoelzer** [jonas-fuchs/virHEAT#18]
Hey, me again : ) 

I am trying to use a GFF annotation from MITOS2 for a mtDNA genome:

[CM022781.1.gff.zip](https://github.com/user-attachments/files/17720558/CM022781.1.gff.zip)

But I get:

```bash
virheat 2024-11-07-vcf-results/vcf-filtered/ results-filtered -g CM022781.1.gff -r CM022781.1

Traceback (most recent call last):
  File "/Users/martin/miniconda3/envs/virheat/bin/virheat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/martin/miniconda3/envs/virheat/lib/python3.12/site-packages/virheat/command.py", line 192, in main
    gff3_info = data_prep.parse_gff3(args.gff3_path, args.reference)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/miniconda3/envs/virheat/lib/python3.12/site-packages/virheat/scripts/data_prep.py", line 310, in parse_gff3
    gff3_dict[gff_values[2]][attribute_id][identifier] = val.replace("\n", "")
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'transcript_trnF(gaa)'
```

So I guess this is a GFF file format you were not expecting ;) 

Any easy way to get that visualized w/ virHEAT? 

(and sorry for repurposing your tool for mtDNA... but it would be very neat also for such an application!)

**Comment by jonas-fuchs** [comment]
Thanks Martin! This is enhancing the tool a bit :)

So basically what I do for the nested dictionary is to set the final keys with the `ID= `identifier. The gff format was not the problem, but in your case  that `exons` only have `parents` .  I have checked quite a few gffs and never seen that there is no unique identifier. I introduced now a simple check if `ID= `is present in each line. 

I also checked NCBI a bit and it seems that exons can have IDs e.g.:

`WJXW01000006.1	Genbank	exon	32023	33421	.	+	.	ID=exon-gnl`

So I think this simple check is ok for now. Probably depends on who annotates these genomes.
