### ISSUE TITLE
A better way to present genes?

### ISSUE THREAD

**Issue by Dx-wmc** [jonas-fuchs/virHEAT#19]
Hi, I am delighted to be using this software. I have a small suggestion. Currently, the gene display is limited to a square shape, which can feel a bit monotonous and doesn’t indicate gene direction. Would it be possible to add an option to choose different shapes, such as arrows, to show gene orientation? Additionally, it would be wonderful if genes on the positive and negative strands could be selectively displayed on two separate rows to improve readability like #17.

**Comment by jonas-fuchs** [comment]
Hi, glad you like it. :) I'll have a look. Arrows should not be a problem I think, but in this case it would not be necessary to display them on two rows.

**Comment by jonas-fuchs** [comment]
Could you do a test drive if that works in your hands (see PR) before I close this issue? 

You can do this by:
```
git clone https://github.com/jonas-fuchs/virHEAT
git checkout gene_vis
pip install .
virheat <your_args> --gene-arrows
```

Arrows are actually quite hard to control, so it might not always look good. I played around a bit and I think I found a decent solution ;).

Here its with my testdata:
[virHEAT_plot.pdf](https://github.com/user-attachments/files/17751096/virHEAT_plot.pdf)

**Comment by Dx-wmc** [comment]
Hi, I followed your method to install and test. For testing the direction of the gene, I manually modified the gff file. Overall, the result looks very good!
[virHEAT_plot-1.pdf](https://github.com/user-attachments/files/17752517/virHEAT_plot-1.pdf)

**Comment by jonas-fuchs** [comment]
Then I will likely merge th pr soon :) Cheers
